Consolidate to one j-job, other changes

diff --git a/UFS-DA/jobs/JUFSDA_GLOBAL_ATMOS_ANALYSIS b/UFS-DA/jobs/JUFSDA_GLOBAL_ATMOS_ANALYSIS
--- a/UFS-DA/jobs/JUFSDA_GLOBAL_ATMOS_ANALYSIS
+++ b/UFS-DA/jobs/JUFSDA_GLOBAL_ATMOS_ANALYSIS
@@ -1,7 +1,7 @@
-#!/bin/ksh
-set -x
+#!/bin/bash
+set -ex
+set -u
 
-export RUN_ENVIR=${RUN_ENVIR:-"nco"}
 export PS4='$SECONDS + '
 date
 
@@ -10,7 +10,6 @@ date
 # Source relevant config files
 #############################
 export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
-configs="base atmanal atmanalrun"
 config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
 for config in $configs; do
     . $config_path/config.$config
@@ -35,7 +34,7 @@ export outid=${outid:-"LL$job"}
 
 export DATA=${DATA:-${DATAROOT}/${jobid:?}}
 mkdir -p $DATA
-cd $DATA
+cd $DATA || (echo "$DATA does not exist. ABORT!"; exit 1)
 
 
 ##############################################
@@ -59,17 +58,14 @@ export pgmerr=errfile
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
 export COMPONENT=${COMPONENT:-atmos}
-if [ $RUN_ENVIR = "nco" ]; then
-    export ROTDIR=${COMROOT:?}/$NET/$envir
-fi
 
 ##############################################
 # Begin JOB SPECIFIC work
 ##############################################
 
 GDATE=$($NDATE -$assim_freq $CDATE)
-gPDY=$(echo $GDATE | cut -c1-8)
-gcyc=$(echo $GDATE | cut -c9-10)
+gPDY=${GDATE:0:8}
+gcyc=${GDATE:8:2}
 GDUMP=${GDUMP:-"gdas"}
 
 export OPREFIX="${CDUMP}.t${cyc}z."
@@ -78,31 +74,18 @@ export APREFIX="${CDUMP}.t${cyc}z."
 export GSUFFIX=${GSUFFIX:-$SUFFIX}
 export ASUFFIX=${ASUFFIX:-$SUFFIX}
 
+export COMOUT=${COMOUT:-$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT}
 
-if [ $RUN_ENVIR = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
-    export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_OBS=${COMIN_OBS:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_GES_OBS=${COMIN_GES_OBS:-$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT}
-else
-    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-    export COMIN_OBS="$DMPDIR/$CDATE/$CDUMP"
-    export COMIN_GES_OBS="$DMPDIR/$GDATE/$GDUMP"
-fi
 mkdir -m 775 -p $COMOUT
+
 # COMIN_GES and COMIN_GES_ENS are used in script
 export COMIN_GES="$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
 export COMIN_GES_ENS="$ROTDIR/enkfgdas.$gPDY/$gcyc/$COMPONENT"
 
 ###############################################################
 # Run relevant script
-env
-msg="HAS BEGUN on $(hostname)"
-postmsg "$jlogfile" "$msg"
-$LOGSCRIPT
 
-
-${UFSDARUNSH:-$SCRgfs/exufsda_global_atmos_analysis_run.sh}
+$EXSCRIPT
 status=$?
 [[ $status -ne 0 ]] && exit $status
 
@@ -116,11 +99,6 @@ status=$?
 if [ -e "$pgmout" ] ; then
   cat $pgmout
 fi
-
-
-msg="ENDED NORMALLY."
-postmsg "$jlogfile" "$msg"
-
 
 ##########################################
 # Remove the Temporary working directory
